### ISSUE TITLE
Starting the app

### ISSUE THREAD

**Issue by sudhanshug16** [Antione7/CrossWord#1]
Hey!

How to start both the apps? 
I mean, I want to run both the apps on a port say 8000.
How can I run both the services?
Please elaborate the procedure. :)

**Comment by Antione7** [comment]
Hi,
There is one app, you transpile angular, but you run Symfony on port 8000,
if I understand what do you want.

See you,
Antoine



Le 10 oct. 2017 21:16, "Sudhanshu Gautam" <notifications@github.com> a
écrit :

**Comment by sudhanshug16** [comment]
Thanks 👍
